---
- hosts: all
  become: yes
  tasks:
  - name: installing apache server
    apt:
      name: apache2
      state: latest
      update_cache: yes
  - name: enabling module
    apache2_module: 
      name: rewrite
      state: present
  - name: Start service httpd, if not started
    service:
        name: apache2
        state: started
  - name: Enable service httpd, and not touch the state
    service:
       name: apache2
       enabled: no
    notify:
      - restart apache2
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    
