---
- hosts: appserver
  become: yes
  tasks:
    - name: installing apache2 on server
      apt:
        name: apache2
        state: present
    - name: Start service httpd, if not started
      service:
        name: apache2
        state: started
      register: mycontent
      ignore_errors: yes
    - name: Enable service httpd, and not touch the state
      service:
        name: apache2
        enabled: yes
      when: ansible_os_family ==  "Debian"
    - name: copy the home page
      template:
        src: apache2.html.j2
        dest: /var/www/html/index.html
    - name: find error
      debug:
        msg: "{{ mycontent.msg }}"
