---
- hosts: appserver
  become: yes
  tasks:
    - name: updating apache server
      command: apt update
    - name: installing apache server
      apt:
        name: apache2
        state: present
      when:  ansible_os_family == "Debian"
      tags:
        - install
    - name: installing httpd server on redhat
      yum:
        name: httpd
        state: present
      when:  ansible_os_family == "RedHat"
      tags:
        - install
        - service
    - name: check memory of Real memroy instance
      debug:
        msg: " Free Ram is {{ansible_memory_mb.real.free}}"
      tags:
        - debug
